# Site
name: "Frontier"
title: "Frontier"
description: "TIL"
logo: 'logo.png'
favicon: 'favicon.png'
baseurl: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  plutonium:
    name: Manav Seksaria
    display_name: Manav Seksaria
    email: meh@notneeded.com
    description: "I got nothin bruh"
  john:
    name: John
    display_name: John    
    email: wowthemesnet@gmail.com
    description: "This is the author box. Write a short description of the author here. You are currently previewing Frontier demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, Helptext.txt]
