# Site
nick: "Asimov"
name: "The Wandering Star"
title: "SEDS Celestia Blog"
description: "An Space blog written and maintained by SEDS Celestia"
logo: 'assets/images/logoWide.png'
favicon: 'favicon.png'
baseurl:
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  plutonium:
    name: plutoniumm
    display_name: plutoniumm
    email: meh@notneeded.com
    description: "I got nothin bruh"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# collections:

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page-:num/

# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile*]
